apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: theresmith/reverseproxy
        # image: ubuntu:groovy
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "1"
          limits:
            memory: "700Mi"
          requests:
            memory: "100Mi"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config    
        - secretRef:
            name: app-secret
        env:
        - name: MESSAGE
          value: "hello world"          
        # command: ["tail"]
        # args: ["-f","/dev/null"]         
        # command: ["printenv"]
        # args: ["POSTGRES_HOST", "POSTGRES_USERNAME", "POSTGRES_PASSWORD","MESSAGE"]